name: 'Hello World!!!'
description: 'Greet someone and record the time'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
  repo-token:
    description: 'Repository token'
    required: true
  fail-on-pattern-missing:
    description: 'Should action fail when pattern matching found nothing'
    required: false
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'dist/index.js'