# Added 10/20/2021
name: Action test for development

# Run only when a PR is opened
on:
  pull_request:
    types: [opened, reopened] #reopened for faster testing
    branches-ignore:
      - "dependabot-npm_and_yarn-*"

jobs:
  update_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Hello world action step
        uses: ./
        id: hello
        with:
          repo-token: "${{ github.token }}"
          who-to-greet: 'Mona the Octocat'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
