name: Simple PR update

on:
  pull_request:
    types: [opened, reopened] #reopened for faster testing
    branches-ignore:
      - "dependabot-npm_and_yarn-*"

jobs:
  update_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Updates Pull Request information
        uses: ./
        with:
          repo-token: "${{ github.token }}"
          head-branch-regex: "(CW|cw)-[0-9]+"
          title-template: "[%headbranch%] "
          body-template: |
              ## :eyes: Jira Ticket: %headbranch%
              :framed_picture: Deploy Preview: https://pr-${{ github.event.number }}.test.co/